export let myArrOfTempIds = [
  [
    '83.2.188',
    'False',
    'False',
    'True',
    '502',
    '',
    'The American Wing',
    '1883',
    'Statuette',
    'Statuett',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '1800–1883',
    '1800',
    '1883',
    'Bronze',
    'H. 9 1/4 in. (23.5 cm)',
    'Gift of William H. Huntington, 1883',
    'Probably made in',
    '',
    '',
    '',
    'Germany',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'http://www.metmuseum.org/art/collection/search/502',
    '',
    '',
    'Metropolitan Museum of Art, New York, NY',
    'Benjamin Franklin|Men|Profiles',
    'http://vocab.getty.edu/page/ulan/500331804|http://…0025928|http://vocab.getty.edu/page/aat/300123319',
    'https://www.wikidata.org/wiki/Q34969|https://www.w…wiki/Q8441|https://www.wikidata.org/wiki/Q4382010',
  ],
  [
    '69.258.4',
    'False',
    'False',
    'True',
    '249',
    '',
    'The American Wing',
    '1969',
    'Side Chair',
    'Side Chair',
    'American',
    '',
    '',
    '',
    '',
    '16497',
    'Maker',
    ' ',
    'Joseph Meeks & Sons',
    'American, New York, 1829–35',
    ' ',
    'Meeks, Joseph & Sons',
    'American',
    '1829      ',
    '1835      ',
    '',
    'http://vocab.getty.edu/page/ulan/500524443',
    'https://www.wikidata.org/wiki/Q97054971',
    '1859',
    '1859',
    '1859',
    'Rosewood',
    '48 x 27 1/2 x 31 in. (121.9 x 69.9 x 78.7 cm)',
    'Gift of Bradford A. Warner, 1969',
    'Made in',
    'New York',
    '',
    '',
    'United States',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'http://www.metmuseum.org/art/collection/search/249',
    '',
    '',
    'Metropolitan Museum of Art, New York, NY',
    'Grapes',
    'http://vocab.getty.edu/page/aat/300379338',
    'https://www.wikidata.org/wiki/Q10978',
  ],
  [
    'X.139.6',
    'False',
    'False',
    'True',
    '2087',
    '',
    'The American Wing',
    '',
    'Pin',
    'Cloak Pin',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '1750–1800',
    '1750',
    '1800',
    'Enamel on copper, brass',
    '1 13/16 x 1 3/8 in. (4.6 x 3.5 cm)',
    'Museum Accession',
    'Made in',
    '',
    '',
    '',
    'England',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'http://www.metmuseum.org/art/collection/search/2087',
    '',
    '',
    'Metropolitan Museum of Art, New York, NY',
    'Portraits|Men|Profiles',
    'http://vocab.getty.edu/page/aat/300015637|http://v…0025928|http://vocab.getty.edu/page/aat/300123319',
    'https://www.wikidata.org/wiki/Q134307|https://www.…wiki/Q8441|https://www.wikidata.org/wiki/Q4382010',
  ],
  [
    'Inst.63.2.60',
    'False',
    'False',
    'True',
    '4071',
    '',
    'The American Wing',
    '',
    'Glass Globe',
    'Glass Globe',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'ca. 1895',
    '1892',
    '1895',
    'Glass',
    'H. 5 5/8 in. (14.3 cm); Diam. 3 3/4 in. (9.5 cm)',
    'Gift of New York Clearing House, 1963',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'http://www.metmuseum.org/art/collection/search/4071',
    '',
    '',
    'Metropolitan Museum of Art, New York, NY',
    '',
    '',
    '',
  ],
  [
    '10.125.698',
    'False',
    'False',
    'True',
    '4769',
    '713',
    'The American Wing',
    '1910',
    'Chair',
    'Leather chair',
    'American',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '1723–45',
    '1723',
    '1745',
    'Soft maple, ash',
    '45 3/4 x 18 1/4 x 14 1/2 in. (116.2 x 46.4 x 36.8 cm)',
    'Gift of Mrs. Russell Sage, 1909',
    'Made in',
    'Boston',
    '',
    '',
    'United States',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'http://www.metmuseum.org/art/collection/search/4769',
    'https://www.wikidata.org/wiki/Q116366276',
    '',
    'Metropolitan Museum of Art, New York, NY',
    '',
    '',
    '',
  ],
  [
    '83.2.398',
    'False',
    'False',
    'True',
    '5039',
    '',
    'The American Wing',
    '1883',
    'Medal',
    'Medal of General Daniel Morgan',
    '',
    '',
    '',
    '',
    '',
    '16357',
    'Maker',
    ' ',
    'Augustin Dupré',
    'French, Saint-Etienne 1748–1833 Armentières-en-Brie',
    ' ',
    'Dupré, Augustin',
    'French',
    '1748      ',
    '1833      ',
    '',
    'http://vocab.getty.edu/page/ulan/500014612',
    'https://www.wikidata.org/wiki/Q767735',
    '1770–1800',
    '1770',
    '1800',
    'Copper',
    'Diam. 2 3/16 in. (5.6 cm)',
    'Gift of William H. Huntington, 1883',
    'Made in',
    '',
    '',
    '',
    'France',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'http://www.metmuseum.org/art/collection/search/5039',
    '',
    '',
    'Metropolitan Museum of Art, New York, NY',
    'Swords|Men',
    'http://vocab.getty.edu/page/aat/300037048|http://vocab.getty.edu/page/aat/300025928',
    'https://www.wikidata.org/wiki/Q12791|https://www.wikidata.org/wiki/Q8441',
  ],
]
